name: Deploy Flask App on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.VM_SSH_KEY }}

    - name: Deploy Flask Docker App on VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          set -e
          cd ~  # change to your actual project directory if needed

          echo "Pulling latest code..."
          git pull origin main

          echo "Checking if container is running..."
          if docker ps -q -f name=flask; then
            echo "Stopping and removing existing flask container..."
            docker stop flask
            docker rm flask
          fi

          echo "Building Docker image..."
          docker build -t flask .

          echo "Running Docker container..."
          docker run -d --name flask -p 3333:5070 flask
        EOF
